### PR TITLE
Delete libvlccore.so.9

### PR DESCRIPTION
**Pull request by Gibberditoslumber**

### CODE REVIEW

**Comment by polybiusproxy** [comment]
make sure it works and i'll merge

**Comment by Gibberditoslumber** [comment]
```bash
avereyconley@penguin:~/FNF-PsychEngine$ lime test linux
source/Achievements.hx:132: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/MainMenuState.hx:66: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/PlayState.hx:369: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/editors/CharacterEditorState.hx:94: characters 3-41 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/editors/DialogueCharacterEditorState.hx:87: characters 3-40 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/options/NoteOffsetState.hx:57: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead

Compiling group: haxe
g++ -Iinclude -I/home/avereyconley/discord_rpc/git/linc/ -I/home/avereyconley/linc_luajit/git//linc/ -I /home/avereyconley/hxCodec/2,5,1/lib/vlc/include/ -I /home/avereyconley/hxCodec/2,5,1/lib/vlc/src/ -c -fvisibility=hidden -O2 -fpic -fPIC -Wno-overflow -DHX_LINUX -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=400(haxe) -m64 -DHXCPP_M64 -I/home/avereyconley/hxcpp/4,2,1/include ... tags=[haxe,static]
 - src/lime/utils/AssetCache.cpp  [haxe,release]
Link: ApplicationMain
```

**Comment by Gibberditoslumber** [comment]
Works!!

**Comment by Gibberditoslumber** [comment]
### DO NOT MERGE
I Made A Mistake

**Pull request closed without merging**
