### PR TITLE
Add "canCrash" variable and fix the KE documentation

### PR DESCRIPTION
**Pull request by TheRealJake12**
the canCrash is used in Blue Balls Incident 2.0 which allows the game to crash itself when the video ends

### CODE REVIEW

**Review by ItsyourboyJonnycat — APPROVED** [review]
please merge it plzzzz

**Comment by polybiusproxy** [comment]
Why add a variable so the game crashes?
I see this pull request unnecessary for a video library.

**Comment by TheRealJake12** [comment]
> Why add a variable so the game crashes? I see this pull request unnecessary for a video library.

for cutscenes that crash the game on purpose. It helps with porting some mods. Its pretty cool though

**Comment by ItsyourboyJonnycat** [comment]
> > Why add a variable so the game crashes? I see this pull request unnecessary for a video library.
> 
> for cutscenes that crash the game on purpose. It helps with porting some mods. Its pretty cool though

yessssss

**Comment by Stilic** [comment]
The crash feature is useless.
This is a video library, not a virus.

**Comment by polybiusproxy** [comment]
> The crash feature is useless. This is a video library, not a virus.

I strongly agree.

**Comment by Stilic** [comment]
> > The crash feature is useless. This is a video library, not a virus.
> 
> I strongly agree.

I think we should close this.

**Comment by TheRealJake12** [comment]
fade-away-oooooooooooo

**Comment by swordcube** [comment]
> > Why add a variable so the game crashes? I see this pull request unnecessary for a video library.
> 
> for cutscenes that crash the game on purpose. It helps with porting some mods. Its pretty cool though

just do Sys.exit() on the video's finishcallback

or purposefully cause a null object reference there

**Comment by TheRealJake12** [comment]
> > > Why add a variable so the game crashes? I see this pull request unnecessary for a video library.
> > 
> > 
> > for cutscenes that crash the game on purpose. It helps with porting some mods. Its pretty cool though
> 
> just do Sys.exit() on the video's finishcallback
> 
> or purposefully cause a null object reference there

bro its easier to do `VideoHandler.canCrash = true;` and remove the finishcallback

**Comment by swordcube** [comment]
> bro its easier to do `VideoHandler.canCrash = true;` and remove the finishcallback

 bro is
 ```
videoHandlerVariable.finishCallback = function() {
     Sys.exit();
}
```

really that hard for you to do

**Comment by TheRealJake12** [comment]
> > bro its easier to do `VideoHandler.canCrash = true;` and remove the finishcallback
> 
>  bro is
>  ```
> videoHandlerVariable.finishCallback = function() {
>      Sys.exit();
> }
> ```
> 
> really that hard for you to do

shhhhhh I also fixed KE documentation so the pr isnt fully useless

**Pull request closed without merging**
