### PR TITLE
MacOS support

### PR DESCRIPTION
**Pull request by Gothbr4dn**
The Mac libs so it works on Mac

### CODE REVIEW

**Comment by BushTrain460615** [comment]
just so you know nothing is coded in yet I just have the libs
I can code them in if you don't want to 
daddy poly

**Comment by trayfellow** [comment]
is this tested yet

**Comment by polybiusproxy** [comment]
Please test it with working footage (build a copy of FNF and record a video playing using hxCodec).
Then send it, and I'll gladly merge this!

**Comment by BushTrain460615** [comment]
Screenshot 2022-06-27 at 3 13 25 PM
here are some of the errors I have before I add the plugins

**Comment by BushTrain460615** [comment]
> Please test it with working footage (build a copy of FNF and record a video playing using hxCodec).
> Then send it, and I'll gladly merge this!

I can't find the plugins which are needed for the video to play

**Comment by BushTrain460615** [comment]
I found them and I have to replace them all so I will make a new commit when I am done

**Comment by BushTrain460615** [comment]
I have about half of them done

**Comment by BushTrain460615** [comment]
I finished importing all the plugins

**Comment by BushTrain460615** [comment]
Screenshot 2022-06-28 at 6 46 11 PM
Only Errors left

**Comment by BushTrain460615** [comment]
fixed it

**Comment by BushTrain460615** [comment]
Screenshot 2022-06-28 at 6 53 56 PM
I think I did something wrong

**Comment by trayfellow** [comment]
> Screenshot 2022-06-28 at 6 53 56 PM
> 
> I think I did something wrong

check your pull requests i think my fix should hopefully fix it cause you did 'macos' instead of just 'mac'

**Comment by trayfellow** [comment]
also if it still doesn't work u prob need to make the plugin files .a files instead of .dylib files

**Comment by trayfellow** [comment]
probably shouldnt mess with the version and release note, thats up to poly to update once the haxelib version is ready to be updated

**Comment by BushTrain460615** [comment]
ok

**Comment by Corrun** [comment]
Sorry if i shouldn't talk here, but does that mean mac support of hxCodec is in the way ?

**Comment by trayfellow** [comment]
> Sorry if i shouldn't talk here, but does that mean mac support of hxCodec is in the way ?

yea, just waiting for bushtrain to get it to work

**Comment by BushTrain460615** [comment]
so I used the wrong version of vlc

**Comment by trayfellow** [comment]
> so I used the wrong version of vlc

its usung version 2.1.2, make sure the mac libs use that version too

**Comment by BushTrain460615** [comment]
ik i was using the latest version at first I just got the libs for 2.1.2

**Comment by BushTrain460615** [comment]
Screenshot 2022-07-05 at 6 18 32 PM
Screenshot 2022-07-05 at 6 21 01 PM

**Comment by Jrgamer4u** [comment]
image

homebrew stuff ... e

**Comment by trayfellow** [comment]
> image
> 
> found this on superuser
> 
> ugh brew shit
> 
> btw all 6 of the missing things are homebrew packages i checked

flightreacts

**Comment by Jrgamer4u** [comment]
😑

**Comment by trayfellow** [comment]
im stuff

**Comment by BushTrain460615** [comment]
https://user-images.githubusercontent.com/72326501/177628414-a9f431a0-3e97-4856-ac45-fe52079bb661.mov

**Comment by BushTrain460615** [comment]
I'm doing Neo

**Comment by BushTrain460615** [comment]
everything is done I just need help with 1 thing
Screenshot 2022-07-06 at 5 33 02 PM

**Comment by trayfellow** [comment]
> everything is done I just need help with 1 thing Screenshot 2022-07-06 at 5 33 02 PM

u forgot to add a slash

i fix it:
https://github.com/BushTrain460615/hxCodec/pull/3

**Comment by BushTrain460615** [comment]
Screenshot 2022-07-06 at 6 16 59 PM
that didn't fix it

**Comment by BushTrain460615** [comment]
never mind it did fix it

**Comment by BushTrain460615** [comment]
Screenshot 2022-07-06 at 6 20 19 PM

**Comment by Jrgamer4u** [comment]
turned into text and uh

```
!<arch>
/       
```

...huh

**Comment by BushTrain460615** [comment]
what

**Comment by trayfellow** [comment]
try making the include folder files be .a file extension instead of .dylib? if that doesnt work maybe you need to make the libvlc and libvlccore files itself a .dylib file extension

**Comment by BushTrain460615** [comment]
it is a .a file
Also do you have discord

**Comment by BushTrain460615** [comment]
Screenshot 2022-07-06 at 8 58 55 PM
Switching to dylib worked

**Comment by BushTrain460615** [comment]
Screenshot 2022-07-06 at 9 01 34 PM

**Comment by BushTrain460615** [comment]
https://user-images.githubusercontent.com/72326501/178042249-996af3d2-a52b-4d50-9f67-d59e06f017b7.mov

how do I code in the videos

**Comment by BushTrain460615** [comment]
https://github.com/BushTrain460615/Neo-Mac-Mp4-test
here is the code

**Comment by trayfellow** [comment]
> https://github.com/BushTrain460615/Neo-Mac-Mp4-test here is the code

whats ur discord

**Comment by BushTrain460615** [comment]
> > https://github.com/BushTrain460615/Neo-Mac-Mp4-test here is the code
> 
> whats ur discord

Bushtrain460615 [RIP TECHNO]#0001

**Comment by BushTrain460615** [comment]
https://user-images.githubusercontent.com/72326501/178106002-dafa1ec1-9f69-405c-a81c-8f3d0e688fa5.mov

**Comment by BushTrain460615** [comment]
Screenshot 2022-07-09 at 6 13 31 PM
Here are some of the files that don't have a spot

**Comment by BushTrain460615** [comment]
@polybiusproxy can you help me with this error
Screenshot 2022-07-09 at 8 23 56 PM

**Comment by BushTrain460615** [comment]
https://github.com/polybiusproxy/hxCodec/projects/1#card-67641989
put this in progress

**Comment by BushTrain460615** [comment]
https://user-images.githubusercontent.com/72326501/178137085-a96e5e11-63b3-4fa6-949e-3e845dcd1158.mov

Here is proof it works so please push it

**Review by JonnycatMeow — APPROVED** [review]
yeeee

**Comment by BushTrain460615** [comment]
I let him test it out

**Comment by polybiusproxy** [comment]
@BushTrain460615 Why are your recordings .mov files? I can't play them 😕

**Comment by BushTrain460615** [comment]
sorry I use Mac I can make them mp4

**Comment by BushTrain460615** [comment]
https://user-images.githubusercontent.com/72326501/178151516-974bec3a-302b-4743-8059-074b6a410459.mp4

**Comment by BushTrain460615** [comment]
also the reason for the sudden cutoff is because it would take too much space

**Comment by BushTrain460615** [comment]
I made it play doctor strange multiverse of madness

**Comment by BushTrain460615** [comment]
@polybiusproxy https://github.com/BushTrain460615/hxCodec/tree/Test/photo's
here are photos so you can see the folders

**Comment by trayfellow** [comment]
WE DID IT OMG

**Review by trayfellow — APPROVED** [review]

**Comment by BushTrain460615** [comment]
https://www.youtube.com/watch?v=UNHmNxzrNGg

**Comment by BushTrain460615** [comment]
here is the proof that it works @polybiusproxy

**Comment by trayfellow** [comment]
oh and put mac support in the hxCodec roadmap card to 'Done' (alongside x86 support too)

**Comment by polybiusproxy** [comment]
Good job!

**Comment by trayfellow** [comment]
LETS GO WE GOT THE DUB

https://youtu.be/g92zRtBhelQ

**Comment by Gothbr4dn** [comment]
Johnny cat taking my old work and making it his own and removing my credit🥀

**Pull request merged**
