### PR TITLE
x86 support

### PR DESCRIPTION
**Pull request by jigsaw-4277821**
it's tested and is working fine!

### CODE REVIEW

**Comment by Raltyro** [comment]
what happened to this pr?
https://github.com/polybiusproxy/hxCodec/pull/118

**Comment by jigsaw-4277821** [comment]
This is even better then that + is tested

**Comment by trayfellow** [comment]
this is a certified hood classic
image

**Comment by polybiusproxy** [comment]
This will take me some minutes to review this PR! 😵

**Pull request merged**
