### PR TITLE
Port some features from my previous rewrite

### PR DESCRIPTION
**Pull request by EliteMasterEric**
This includes:

- New FlxVideoState and FlxCutsceneState
  - The former provides a convenient and bug-free interface to create an FlxState which plays a video.
  - The latter provides a convenient and bug-free interface to move to a new state, play a video, then move back to a new state of your choice.
- `Callback` handler class (which uses FlxTypedSignal if Fixel is available and a custom implementation otherwise), to allow for multiple callback functions on one signal without breaking things when one user overrides a callback that is being used already.
  - I tried my best to make this change backwards compatible but it may break code in some cases.
- Added additional callbacks:
  - `onOpening`
  - `onPlaying`
  - `onPaused`
  - `onStopped`
  - `onEndReached`
  - `onEncounteredError`
  - `onForward`
  - `onBackward`
- Added the `IVideoPlayer` interface, to ensure that all video playback classes have the same functions available.
- Added additional sample projects

This PR supercedes #241 , which was based on LibVLC 4.0 and had many stability issues.

### CODE REVIEW

**Review by polybiusproxy — COMMENTED** [review]
Looks good, how does it run performance-wise?

**Comment by MAJigsaw77** [comment]
> Looks good, how does it run performance-wise?

It's still in development as there's something stiff missing for now, like asynchonously parse and working logging

**Comment by EliteMasterEric** [comment]
I would like to end up closing this PR and establishing a system where the `develop` branch is used for bleeding edge/development builds, and `main` always contains the source for latest stable release.

Performance seems comparable overall to older versions, Rapper GF's performance PR will probably help a lot. I need to do a proper review of those changes myself.

**Comment by polybiusproxy** [comment]
> I would like to end up closing this PR and establishing a system where the `develop` branch is used for bleeding edge/development builds, and `main` always contains the source for latest stable release.
> 
> Performance seems comparable overall to older versions, Rapper GF's performance PR will probably help a lot. I need to do a proper review of those changes myself.

Sounds good! 👍

**Comment by EliteMasterEric** [comment]
Closing this since `develop` is now the active development branch. We'll fast-foward `main` once we are ready to publish the next release.

**Pull request closed without merging**
