### PR TITLE
Better README and Haxelib JSON

### PR DESCRIPTION
**Pull request by Stilic**
idk just fixed the entire readme and removed the mp4 tag because this lib supports multiple video formats.

### CODE REVIEW

**Comment by TheRealJake12** [comment]
what are all the video formats?

**Comment by Jrgamer4u** [comment]
> what are all the video formats?

in the [mux files](https://github.com/polybiusproxy/hxCodec/tree/main/include/plugins/mux) there are 8 formats + dummy
asf, avi, mp4, mpjpeg, ogg, ps, ts, wav
btw i'm pretty sure that's a [_bit_ less than vlc actually supports](https://wiki.videolan.org/VLC_Features_Formats/)

**Comment by Jrgamer4u** [comment]
> what are all the video formats?

best place to look is most likely in the [mux](https://github.com/polybiusproxy/hxCodec/tree/main/include/plugins/mux) or [demux](https://github.com/polybiusproxy/hxCodec/tree/main/include/plugins/demux) plugins for the list

**Comment by TheRealJake12** [comment]
I already tested MP4, WEBM, And MOV and they work perfectly good job

**Comment by polybiusproxy** [comment]
technically, hxCodec supports every video format you can play on VLC.

**Comment by Stilic** [comment]
> technically, hxCodec supports every video format you can play on VLC.

Please, can you merge this pull request?

**Pull request merged**
