### PR TITLE
[TESTING NEEDED] x86 version of libvlc and libvlccore 

### PR DESCRIPTION
**Pull request by Jrgamer4u**
NOTICE: THIS NEEDS TO BE TESTED. If you have a 32bit computer, test this out; If it doesn't work, use the steps below and do a pull request to [Jrgamer4u:x86-libs](https://github.com/Jrgamer4u/hxCodec/tree/x86-libs).

i generated it using: https://wiki.videolan.org/GenerateLibFromDll/

What i used to generate libvlc.lib
```
echo EXPORTS > libvlc.def
for /f "usebackq tokens=4,* delims=_ " %i in (`dumpbin /exports "libvlc.dll"`) do if %i==libvlc echo %i_%j >> libvlc.def
lib /def:libvlc.def /out:libvlc.lib /machine:x86
```

What i used to generate libvlccore.lib
```
dumpbin /exports "libvlc.dll" > "libvlc.def"
```
modified the file so it's like libvlc.def
```
lib /def:libvlccore.def /out:libvlccore.lib /machine:x86
```

If it doesn't work because i did it incorrectly somehow generate it yourself

i would have just put this in discussions for someone else to get credit but there is no discussions page i couldn't be lazy :(((((((((

### CODE REVIEW

**Comment by TheRealJake12** [comment]
what exactly does this do?

**Comment by Jrgamer4u** [comment]
> what exactly does this do?

it just adds the x86 version of libvlc and libvlccore
[the card saying he just needs the above stuff](https://github.com/polybiusproxy/hxCodec/projects/1#card-67641915)
idk if he adds other stuff for support i'm just gonna add the x86 version of libvlc and libvlccore + editing LibVLCBuild.xml
I'll gon' make another commit soon to make some changes

**Comment by Jrgamer4u** [comment]
i noticed that both the libs were very smaller for x64, libvlc 254 kb to 82 kb, libvlccore 578 kb to 1.5 kb
i'm starting to worry if the libs work or not
if they do, i wonder why they were so big

**Comment by polybiusproxy** [comment]
before merging, was this tested? @Jrgamer4u

**Comment by Jrgamer4u** [comment]
> before merging, was this tested? @Jrgamer4u 

i dont have an x86 computer that can run fnf

i forgot to test the new x64 libs

**Comment by Jrgamer4u** [comment]
new x64 libs didn't work bc i think x64 [is not listed???
the default is x86](https://web.archive.org/web/20090123025542/http://www.coderetard.com/2009/01/21/generate-a-lib-from-a-dll-with-visual-studio/)

**Comment by McJonnycat** [comment]
will this generating think work for macos? cause im trying to get the static lib for it which is the .a file

**Comment by Jrgamer4u** [comment]
> will this generating think work for macos? cause im trying to get the static lib for it which is the .a file

it only makes .lib files

**Comment by McJonnycat** [comment]
oh ok

**Comment by Jrgamer4u** [comment]
idk how to define the x64 and x86 stuff so that it just connects with the export

**Review by Stilic — APPROVED** [review]
this just ready to be merged without any testing i suppose (will be hard to find people, maybe check on the fnf psych engine discord).

**Review by polybiusproxy — COMMENTED** [review]
once this is tested, it'll be merged
as @Stilic said, as on a fnf modding discord for someone with a x86 machine

**Comment by Jrgamer4u** [comment]
i don't use discord anymore because of reasons
ill allow the pr to stay in limbo

**Comment by MacXPBelow** [comment]
i can test this

**Comment by polybiusproxy** [comment]
> i can test this

Please test it ASAP since I was unable to do it all this time. Tell me how it went.

**Comment by McJonnycat** [comment]
> Sure, gonna test it tomorrow.

can you do mac?

**Comment by MacXPBelow** [comment]
Yea, i have both.

**Comment by McJonnycat** [comment]
can you make the vlc for mac

**Comment by MacXPBelow** [comment]
I don't know how to make it though.

**Comment by McJonnycat** [comment]
see instructions here https://github.com/jigsaw-4277821/hxvlc/blob/main/README.md

**Comment by McJonnycat** [comment]
just scroll down for the macos instructions

**Comment by MacXPBelow** [comment]
OK.

**Comment by MacXPBelow** [comment]
No problem.

**Comment by Stilic** [comment]
> see instructions here https://github.com/jigsaw-4277821/hxvlc/blob/main/README.md

this is not hxcodec, this is a another lib
why are you saying lies bruh?

**Comment by McJonnycat** [comment]
im not and i know its hxvlc aka jigsaws version but thats the only way

**Comment by McJonnycat** [comment]
plus i wanted to put it here but poly didn't want to accept my pull request

**Comment by Stilic** [comment]
> im not and i know its hxvlc aka jigsaws version but thats the only way

bro this is the hxcodec repo
just port code to this lib instead

**Comment by Stilic** [comment]
> > im not and i know its hxvlc aka jigsaws version but thats the only way
> 
> bro this is the hxcodec repo
just port code from hxvlc to our lib instead

**Comment by McJonnycat** [comment]
> > > im not and i know its hxvlc aka jigsaws version but thats the only way
> 
> bro this is the hxcodec repo just port code from hxvlc to our lib instead

yeah but here is the thing its dylibs so its not gonna work

**Comment by McJonnycat** [comment]
and plus i have tried

**Comment by Stilic** [comment]
> and plus i have tried

ok
i will see if i can make these works on hxcodec myself

**Comment by McJonnycat** [comment]
ok bet

**Comment by Stilic** [comment]
also we are not in the good place for talk about this

**Comment by McJonnycat** [comment]
so where do we talk?

**Comment by Stilic** [comment]
> so where do we talk?

maybe in a new issue or discusssion

**Comment by McJonnycat** [comment]
ok

**Comment by Jrgamer4u** [comment]
every time i get a message from here my phone shakes like there's an earth quake at 11 pm

**Comment by McJonnycat** [comment]
> every time i get a message from here my phone shakes like there's an earth quake at 11 pm

lol

**Comment by MacXPBelow** [comment]
I am gonna start testing, i am installing necessary things rn

**Comment by MacXPBelow** [comment]
Visual Studio do not work at all at 32 bit systems, i could not build the game.

**Comment by ItsyourboyJonnycat** [comment]
> Visual Studio does not work at all at 32 bit systems, i could not build the game.

yeah it does you can download it for 32 bit

**Comment by ItsyourboyJonnycat** [comment]
https://code.visualstudio.com/download#

**Pull request closed without merging**
