### PR TITLE
hxCodec 3.0 Rewrite

### PR DESCRIPTION
**Pull request by EliteMasterEric**
Redo of #236.

Um okay trying to use Git LFS was like pouring water on a grease fire but this should be fixed now.

Sadly I had to squash a bunch of my commits but things look good now.

# To-Dos
- [x] Tested working on Windows
- [X] Tested working on Linux
- [x] Move loggingv3 to Windows
- [ ] Tested working on Android
- [ ] Tested working on Mac

NOTE: In order to use this haxelib from Git, you currently need to extract this ZIP file and place its contents in the `thirdparty/` folder. They have to be distributed separately because there are dozens of files, totaling to over a gigabyte, some of which are over Github's limit of 100mb. We may need to look into potential file hosts, or whether we can automate this download somehow (they are available individually on nightlies.videolan.org within different ZIPs).

(UPDATED MARCH 1, 2023) https://mega.nz/file/Hssi2LZJ#f579LZw5i9t5-0KsklwzErfODqQkWUExkzMYDUIk_WA

### CODE REVIEW

**Comment by EliteMasterEric** [comment]
Trying to build on Android I get this error

```
Error: In file included from E:/Programming/Haxe/hxcodec/thirdparty/include/vlc/vlc.h:39:0,
                 from ./src/hxcodec/_internal/LibVLCMediaPlayerHelper.cpp:5:
E:/Programming/Haxe/hxcodec/thirdparty/include/vlc/libvlc.h:50:28: error: expected '}' before '__attribute__'
 # define LIBVLC_DEPRECATED __attribute__((deprecated))
                            ^
E:/Programming/Haxe/hxcodec/thirdparty/include/vlc/libvlc_events.h:186:35: note: in expansion of macro 'LIBVLC_DEPRECATED'
     libvlc_MediaListViewItemAdded LIBVLC_DEPRECATED =0x300,
                                   ^
In file included from E:/Programming/Haxe/hxcodec/thirdparty/include/vlc/vlc.h:47:0,
                 from ./src/hxcodec/_internal/LibVLCMediaPlayerHelper.cpp:5:
E:/Programming/Haxe/hxcodec/thirdparty/include/vlc/libvlc_events.h:186:53: error: expected unqualified-id before '=' token
     libvlc_MediaListViewItemAdded LIBVLC_DEPRECATED =0x300,
                                                     ^
In file included from ./src/hxcodec/_internal/LibVLCMediaPlayerHelper.cpp:5:0:
E:/Programming/Haxe/hxcodec/thirdparty/include/vlc/vlc.h:53:1: error: expected declaration before '}' token
 }
```

**Comment by polybiusproxy** [comment]
> Um okay trying to use Git LFS was like pouring water on a grease fire but this should be fixed now.

Oh, so that's why I got an email saying my Git LFS plan was disabled.

**Comment by JonnycatMeow** [comment]
is the libvlc still 4.0

**Comment by EliteMasterEric** [comment]
> is the libvlc still 4.0

Yes

**Comment by JonnycatMeow** [comment]
@EliteMasterEric do i still need to test out the mac one

**Comment by BushTrain460615** [comment]
I can also help with Mac stuff

**Comment by JonnycatMeow** [comment]
is the project still being continued?

**Comment by EliteMasterEric** [comment]
Superceded by #263.

**Pull request closed without merging**
