### PR TITLE
Added Volume multiplier and canAutoPause

### PR DESCRIPTION
**Pull request by KirbyKid256**
So I made another fork that's actually more useful than my first one. I mainly added two more variables to `VideoHandler`.

**volumeMult:Float = 1**
Currently, the volume solely depends on the game volume or if the video's `canUseSound` variable is false. If canUseSound is false, the volume is always 0. If it's true, then the volume depends on `FlxG.sound.volume` and the FlxG sound system. The `volumeMult` variable allows for videos to have unique volume settings and is helpful if one video is quieter or louder than the music.

**canAutoPause:Bool = true**
By default, videos always auto-pause when `FlxG.autoPause` is true. This is fine for regular video cutscenes but is NOT helpful with `VideoSprites` in a game that has a `PauseSubState`. For example, in Friday Night Funkin' where you can pause the game, I've made it so that on pause, the VideoSprites pause as well. However, when I lose and then regained focus of the game, the VideoSprite would start playing again even when the game should be paused. Even when I had it constantly updated to be paused while the game was paused, the video kept unpausing briefly before pausing.
This is simply an extra variable where before you play the video, you can turn `canAutoPause` off so the video doesn't autopause on focus lost. In turn, you will need to manually make a function somewhere else that will pause the video on focus lost. This allowed me to make it so that VideoSprites only auto pause and auto resume while `paused` is false.

### CODE REVIEW

**Comment by MAJigsaw77** [comment]
`volumMutl` makes literally no sense

**Comment by MAJigsaw77** [comment]
canUseSound by default is true if you don't know

**Comment by MAJigsaw77** [comment]
`canAutoPause` thing might be useful but not `volumeMult`

**Comment by EliteMasterEric** [comment]
Note that #236 is a major breaking change and will override or conflict with this if it gets merged.

**Comment by MAJigsaw77** [comment]
> Note that #236 is a major breaking change and will override or conflict with this if it gets merged.

When that pr will have all platforms support working we can't stay without to accept prs if they come ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯

**Comment by KirbyKid256** [comment]
> `volumMutl` makes literally no sense

You can't change the volume of the video without changing the volume of the game to false. `FlxG.sound.volume * 100` Is what's doing it. Meaning if `FlxG.sound.volume = 0.5`, then the volume will ALWAYS be 50. You can't change the video volume other than changing `FlxG.sound.volume`. I've already tried setting the volume variable manually, but it always returns `FlxG.sound.volume * 100` EXCLUDING whether or not `canUseSound` is false which will make the volume output 0.

I also made it so that `volumeMult` is a public variable which means that it can be easily altered for any video. Adding an extra variable can be used to actually manipulate the volume of the video further than just `FlxG.sound.volume * 100` because `volume = 150` doesn't work. It always outputs: 
`volume = Std.int(#if FLX_SOUND_SYSTEM ((FlxG.sound.muted || !canUseSound) ? 0 : 1) * #else (!canUseSound ? 0 : 1) * #end FlxG.sound.volume * 100);`

This simply adds more functionality to how the volume works. Meaning if  `FlxG.sound.volume = 1` and `volumeMult = 1.5`, then the output volume is 150 rather than 100 as it would be without the variable. Do I need to make a video to explain this further?

**Comment by MAJigsaw77** [comment]
The volume needs to be exactly like how is `FlxG.sound.volume` one

**Comment by MAJigsaw77** [comment]
Without modifiers

**Comment by EliteMasterEric** [comment]
not sure why this got closed but Git won't let me reopen it

**Pull request closed without merging**
