### PR TITLE
hxCodec Manipulate Video through Haxe

### PR DESCRIPTION
**Pull request by KirbyKid256**
I wanted to edit the build of hxCodec so I can mess with the video through FunkinLua. I'm overhauling the entire video system in Psych Engine for more video manipulation.
All I did so far was make the functions in VLCBitmap from `get_time` to `get_fps` public.

### CODE REVIEW

**Comment by MAJigsaw77** [comment]
This is useless

**Comment by MAJigsaw77** [comment]
You can get these from the vars without to make that functions public

**Comment by KirbyKid256** [comment]
You know, my fork also included setting the functions. If you can get AND set variables without making the functions public, can you give me some examples?

**Comment by MAJigsaw77** [comment]
You don't need functions for anything -__-

**Comment by KirbyKid256** [comment]
Nope. But now I feel like an idiot.
I actually figured it out right before you gave me the examples.

**Comment by MAJigsaw77** [comment]
You wanted examples, I gived you them

**Comment by KirbyKid256** [comment]
Yes, and they're very helpful. So thank you.

**Pull request closed without merging**
