### PR TITLE
Delete libvlccore.so.9

### PR DESCRIPTION
**Pull request by Gibberditoslumber**

### CODE REVIEW

**Comment by Gibberditoslumber** [comment]
Work's 👍

**Comment by BeastlyGhost** [comment]
that literally doesn't help with anything, in fact the error was fixed already, you're basically breaking it again

**Comment by BeastlyGhost** [comment]
and I know for a fact that this is to fix Psych Engine's Video Linux support, it's not a problem with the main repository for hxCodec, it's a problem with Psych Engine itself, and it will be fixed if it's *really* necessary and if we find why the issue happens in the first place

**Comment by Gibberditoslumber** [comment]
> that literally doesn't help with anything, in fact the error was fixed already, you're basically breaking it again

Okay

**Pull request closed without merging**
