### PR TITLE
Fixing the MP4 sprite if you press enter in game + adding the android back button to finish the video in android 

### PR DESCRIPTION
**Pull request by jigsaw-4277821**

### CODE REVIEW

**Comment by sussycatboy** [comment]
This is Amazing you are so incredible Saw!!

**Comment by Gottypa** [comment]
That's actually very useful, thx for that.

**Comment by Hyper183** [comment]
Omg finally thanks 🫂

**Comment by polybiusproxy** [comment]
yep, these are bot accounts...

**Pull request merged**
