### PR TITLE
hxCodec 3.0 rewrite (video controls, LibVLC 4.0, and more)

### PR DESCRIPTION
**Pull request by EliteMasterEric**
This version is a full rewrite by EliteMasterEric, based on the old codebase, with new features and improvements.

## Added
- Added premade classes for video playback on HaxeFlixel.
    - Added `FlxVideoState` which plays videos.
    - Added `FlxVideoSubState` which plays videos.
    - Added `FlxCutsceneState` which plays a specific video (with the option to skip) before switching to the next state.
- All video player classes now have new video controls and metadata available.
    - Play a video (or switch what video is playing) with `video.playVideo`
    - Pause the video with `video.pause`
    - Resume the video with `video.resume`
    - Toggle played/paused with `video.togglePaused`
    - Stop the video with `video.stop`
    - Seek in the video by timestamp with `video.time`
    - Seek in the video by percent complete with `video.position`
    - Set volume with `video.volume`
    - Mute audio with `video.muteAudio`
    - Set playback rate with `video.playbackRate`
    - Fetch the video duration with `video.duration`
    - Check if video is playing with `video.isPlaying`
- All video player classes now utilize a new standardized callback/listener system.
    - This is based on FlxSignal if it is available, and its own implementation if FlxSignal is not available.
    - Available callbacks include `onOpening`, `onPlaying`, `onPaused`, `onStopped`, `onEndReached`, `onEncounteredError`, `onForward`, `onBackward`.
    - Use `onEndReached.add(funcToCall)` to add a callback to be executed each time the video ends.
    - Use `onEndReached.addOnce(funcToCall)` to add a callback to be executed only once.
    - Use `onEndReached.remove(funcToCall)` to remove an existing callback.
- Added new sample projects to demonstrate the use of the library.
    - These sample projects do not include video files to minimize repo size. Please make sure to download the videos for the sample projects before testing.
## Changed
- Reworked classes for video playback for HaxeFlixel and OpenFL.
    - `FlxVideoSprite` for HaxeFlixel can be added to a scene to play a video.
    - `VideoSprite` for OpenFL can be added as a sprite to play a video.
- All video players now use an `IVideoPlayer` interface, which ensures all video player classes support the same controls.
- Reworked internal library code to use LibVLC 4.0.
    - This lays the groundwork for future features and performance improvements.
- Refactored codebase for improved readability and maintainability.
- Added new documentation for most functions.
- Added Haxe Checkstyle to maintain consistent code style and formatting in Haxe code.
## Known Issues
- Support for Mac, Linux, and Android is currently not tested and may not be functional.
- Support for iOS is in progress and is not currently functional.

### CODE REVIEW

**Review by TheKitBoi — APPROVED** [review]

**Comment by MAJigsaw77** [comment]
I think we must make `Mac`, `Linux`, `Android` and `iOS` functional because pushing

**Comment by EliteMasterEric** [comment]
> I think we must make `Mac`, `Linux`, `Android` and `iOS` functional before pushing

I can do some work on Linux and Android but I'm kind of busy. Mac I can't do the work for as I don't have a Mac.

iOS is complicated and might need to be pushed off until later, because it requires using [vlcKit](https://code.videolan.org/videolan/VLCKit) and also I've never worked with iOS before and also I don't own a Mac

**Review by MemeHovy — APPROVED** [review]
amazing :D

**Comment by BeastlyGabi** [comment]
wouldn't it be necessary to mark this PR as a draft for the time being? to avoid accidental merges and such

**Comment by mayo78** [comment]
this compiles fine, but when opening the exported exe it gives the error "[exe name] - Entry Point Not Found" "The procedure entry point libvlc_media_get_parsed_status could not be located in the dynamic link library [path of exe]"

**Comment by EliteMasterEric** [comment]
> this compiles fine, but when opening the exported exe it gives the error "[exe name] - Entry Point Not Found" "The procedure entry point libvlc_media_get_parsed_status could not be located in the dynamic link library [path of exe]"

Which operating system is this

**Comment by JonnycatMeow** [comment]
gonna make ios fixes and i am gonna test it

**Review by Raltyro — APPROVED** [review]

**Comment by Raltyro** [comment]
wwait, does stuff actually works in other platforms?

**Comment by TheRealJake12** [comment]
> wwait, does stuff actually works in other platforms?

no (I have been told it doesn't.)

**Comment by polybiusproxy** [comment]
> > wwait, does stuff actually works in other platforms?
> 
> no (I have been told it doesn't.)

Support is there but it has yet to be tested.

**Comment by mayo78** [comment]
> > > wwait, does stuff actually works in other platforms?
> > 
> > 
> > no (I have been told it doesn't.)
> 
> Support is there but it has yet to be tested.

tested on mac, didn't work

**Comment by ACrazyTown** [comment]
I'm having an issue where a FlxVideoSprite just doesn't render if it's `cameras` is set to a camera different than `FlxG.camera`

**Comment by EliteMasterEric** [comment]
> I'm having an issue where a FlxVideoSprite just doesn't render if it's `cameras` is set to a camera different than `FlxG.camera`

Does this issue happen on the old version of hxCodec?

I think this might be related to a similar issue where videos don't work on substates.

The most stable thing to do right now is to use FlxVideoState or FlxCutsceneState (which uses FlxVideoState).

**Review by BombasticTom — APPROVED** [review]
Peak

**Comment by BombasticTom** [comment]
umm why does it have branch conflicts?

**Comment by mitaka78** [comment]
Is it possible to make a video restartable with this version? Once a video ends it seems I'm unable to set back the time to 0.
Looping does not work as I'm implementing a video component in my program that can pause/restart

**Comment by mitaka78** [comment]
> Is it possible to make a video restartable with this version? Once a video ends it seems I'm unable to set back the time to 0. Looping does not work as I'm implementing a video component in my program that can pause/restart

So far my only succesfully implementation of this was just running playVideo() again.

**Comment by MAJigsaw77** [comment]
> Is it possible to make a video restartable with this version? Once a video ends it seems I'm unable to set back the time to 0. Looping does not work as I'm implementing a video component in my program that can pause/restart

which platform are you using?

**Comment by EliteMasterEric** [comment]
> Is it possible to make a video restartable with this version?

I will look into this later if I have the time. Still working on getting Linux working.

**Comment by EliteMasterEric** [comment]
Updates on the status of this repo:

- Logging has been improved with help of KadeDev. This should help with the next point...
- Linux builds and runs but fails to properly parse the media.
- Mac has not been tested and needs testers.
- Android has not been tested.
- iOS has not been tested and will likely need a refactor, or iOS specific code. This is difficult since I do not currently have access to a Mac.

**Comment by JonnycatMeow** [comment]
bruh i did test the mac but i did not test the ios

**Comment by BombasticTom** [comment]
I have an android but dunno how to test it

**Comment by JonnycatMeow** [comment]
damn

**Comment by EliteMasterEric** [comment]
This was closed due to Git tomfuckery, I might need to make another PR but this is still in active development.

**Pull request closed without merging**
