### PR TITLE
Turning this into a haxe lib + adding android support + increased video framerate (60 FPS +)

### PR DESCRIPTION
**Pull request by jigsaw-4277821**

### CODE REVIEW

**Comment by Sirox228** [comment]
very cool :) support 👍

**Comment by zacksgamerz** [comment]
i approve of this pull request

**Comment by An-undertale-fan** [comment]
Cool

**Comment by Randomxdp** [comment]
Cool

**Comment by Ateriking** [comment]
Great

**Comment by Gottypa** [comment]
Good

**Comment by NiceArgument** [comment]
Noice

**Comment by polybiusproxy** [comment]
why does the comments look like bots
anyway good job

**Comment by Randomxdp** [comment]
> why does the comments look like bots anyway good job

He just told everyone in disc to support the pr

**Pull request merged**
